export const FETCH_AUTO_LIST = 'AUTO/FETCH_AUTO_LIST'
export const FETCH_AUTO_ALL = 'AUTO/FETCH_AUTO_ALL'
export const FETCH_AUTO = 'AUTO/FETCH_AUTO'
export const ADD_END_DATE = 'CALEN/ADD_END_DATE '
export const ADD_START_DATE = 'ADD_START_DATE'
export const ADD_AUTO = "ADD_AUTO"
export const ADD_AUTO_OPTIONS = 'ADD_AUTO_OPTIONS'
